import { ROLES, Role } from './roles';

export const PERMISSIONS = {
  STUDENT_ACCESS: 'student:access',
  WARDEN_ACCESS: 'warden:access',
  FACULTY_ACCESS: 'faculty:access',
  ADMIN_ACCESS: 'admin:access',
  APPROVE_OUTPASS: 'outpass:approve',
  MANAGE_COMPLAINTS: 'complaints:manage',
  VIEW_ATTENDANCE: 'attendance:view',
  TRIGGER_SOS: 'sos:trigger',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS_MAP: Record<Role, string[]> = {
  [ROLES.STUDENT]: [PERMISSIONS.STUDENT_ACCESS, PERMISSIONS.TRIGGER_SOS],
  [ROLES.WARDEN]: [
    PERMISSIONS.WARDEN_ACCESS,
    PERMISSIONS.APPROVE_OUTPASS,
    PERMISSIONS.MANAGE_COMPLAINTS,
    PERMISSIONS.TRIGGER_SOS,
  ],
  [ROLES.FACULTY]: [
    PERMISSIONS.FACULTY_ACCESS,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.MANAGE_COMPLAINTS,
    PERMISSIONS.TRIGGER_SOS,
  ],
  [ROLES.ADMIN]: [
    PERMISSIONS.ADMIN_ACCESS,
    PERMISSIONS.WARDEN_ACCESS,
    PERMISSIONS.FACULTY_ACCESS,
    PERMISSIONS.APPROVE_OUTPASS,
    PERMISSIONS.MANAGE_COMPLAINTS,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.TRIGGER_SOS,
  ],
  [ROLES.SUPER_ADMIN]: [
    PERMISSIONS.ADMIN_ACCESS,
    PERMISSIONS.WARDEN_ACCESS,
    PERMISSIONS.FACULTY_ACCESS,
    PERMISSIONS.APPROVE_OUTPASS,
    PERMISSIONS.MANAGE_COMPLAINTS,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.TRIGGER_SOS,
  ],
};

export function hasPermission(userPermissions: string[], requiredPermission: string): boolean {
  return userPermissions.includes(requiredPermission);
}
